### ISSUE TITLE
gravatar causing error

### ISSUE THREAD

**Issue by andringle** [N0rz3/Zehef#14]
Gravatar
Traceback (most recent call last):
  File "/home/osint/Desktop/tools/zehef/Zehef/zehef.py", line 5, in <module>
    from main import main; asyncio.run(main())
                           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/osint/Desktop/tools/zehef/Zehef/main.py", line 10, in main
    await parser()
  File "/home/osint/Desktop/tools/zehef/Zehef/lib/cli.py", line 58, in parser
    await instagram(target)
  File "/home/osint/Desktop/tools/zehef/Zehef/modules/accounts/instagram.py", line 8, in instagram
    csrf_token = req.cookies['csrftoken']
                 ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/osint/.local/lib/python3.12/site-packages/httpx/_models.py", line 1157, in __getitem__
    raise KeyError(name)
KeyError: 'csrftoken'


program stops at gravatar

**Comment by Dehnzel08** [comment]
Same here. It works at first, but after a while I'm receiving the error. I'm guessing we need proxies for this?

**Comment by N0rz3** [comment]
Hi so personally I don't receive any errors, so yes it's probably a ratelimit try again with a proxy or vpn
