### ISSUE TITLE
KeyError: 'csrftoken'

### ISSUE THREAD

**Issue by Korenely** [N0rz3/Zehef#17]
```
Traceback (most recent call last):
  File "/home/danylo/Zehef/zehef.py", line 5, in <module>
    from main import main; asyncio.run(main())
                           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/danylo/Zehef/main.py", line 10, in main
    await parser()
  File "/home/danylo/Zehef/lib/cli.py", line 58, in parser
    await instagram(target)
  File "/home/danylo/Zehef/modules/accounts/instagram.py", line 8, in instagram
    csrf_token = req.cookies['csrftoken']
                 ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/danylo/Zehef/venv/lib64/python3.12/site-packages/httpx/_models.py", line 1148, in __getitem__
    raise KeyError(name)
KeyError: 'csrftoken'
```
I ran it with this command:
python3 zehef.py example@gmail.com

python version: 3.12

**Comment by N0rz3** [comment]
Hi, I see that there are quite a few people who find themselves in the same situation as you. The code of "Zehef" has just been modified to avoid a crash of the tool.
